# Generated by Django 6.0.5 on 2026-06-04 01:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        default="fa-tag",
                        help_text="Classe FontAwesome (ex: fa-book)",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#fec89a", help_text="Couleur hex", max_length=7
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "Question générale"),
                            ("SUPPORT", "Support technique"),
                            ("PARTNERSHIP", "Partenariat"),
                            ("ISSUE", "Signaler un problème"),
                            ("FEEDBACK", "Retour/Suggestion"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("responded", models.BooleanField(default=False)),
                ("response", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Message Contact",
                "verbose_name_plural": "Messages Contact",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Laisser vide pour gratuit",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("image", models.ImageField(upload_to="listings/")),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("NEW", "Neuf"),
                            ("LIKE_NEW", "Comme neuf"),
                            ("GOOD", "Bon état"),
                            ("FAIR", "État correct"),
                            ("SERVICE", "Service"),
                        ],
                        default="LIKE_NEW",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(help_text="Bâtiment/Campus", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SOLD", "Vendu/Complété"),
                            ("ARCHIVED", "Archivé"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "contact_method",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("PHONE", "Téléphone"),
                            ("IN_PERSON", "En personne"),
                            ("BOTH", "Email + Téléphone"),
                        ],
                        default="EMAIL",
                        max_length=20,
                    ),
                ),
                ("views_count", models.IntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Auto-archivé si non actualisé", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listings",
                        to="app.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annonce",
                "verbose_name_plural": "Annonces",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="listings/gallery/")),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="app.listing",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "Quotidienne"),
                            ("WEEKLY", "Hebdomadaire"),
                            ("MONTHLY", "Mensuelle"),
                        ],
                        default="WEEKLY",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("token", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="subscribers", to="app.category"
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription Newsletter",
                "verbose_name_plural": "Inscriptions Newsletter",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university", models.CharField(default="UPC", max_length=100)),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("DROIT", "Droit"),
                            ("ECONOMIE", "Économie"),
                            ("MEDECINE", "Médecine"),
                            ("THEOLOGIE", "Théologie"),
                            ("INFORMATIQUE", "Informatique"),
                        ],
                        default="INFORMATIQUE",
                        max_length=50,
                    ),
                ),
                (
                    "promotion",
                    models.CharField(help_text="Ex: 2024-2025", max_length=50),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "verification_token",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("total_reviews", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Étudiant",
                "verbose_name_plural": "Profils Étudiants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="app.studentprofile",
            ),
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="app.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="app.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Favori",
                "verbose_name_plural": "Favoris",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("COMPLETED", "Complétée"),
                            ("FAILED", "Échouée"),
                            ("REFUNDED", "Remboursée"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("TRANSFER", "Virement bancaire"),
                            ("CARD", "Carte bancaire"),
                            ("CASH", "Espèces"),
                            ("PAYPAL", "PayPal"),
                            ("CRYPTO", "Cryptomonnaie"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchases",
                        to="app.studentprofile",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="app.listing",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to="app.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("NOTES", "Notes de cours"),
                            ("EXAM", "Examen/Correction"),
                            ("SUMMARY", "Résumé"),
                            ("CHEAT_SHEET", "Antisèche"),
                            ("PROJECT", "Projet"),
                            ("RESOURCE", "Ressource"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/")),
                (
                    "subject",
                    models.CharField(
                        blank=True, help_text="Ex: Mathématiques", max_length=100
                    ),
                ),
                (
                    "course_code",
                    models.CharField(
                        blank=True, help_text="Ex: MATH101", max_length=50
                    ),
                ),
                (
                    "semester",
                    models.CharField(blank=True, help_text="Ex: S1", max_length=50),
                ),
                ("year", models.IntegerField(default=2026)),
                ("downloads_count", models.IntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, help_text="Taille en bytes", null=True
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("DOCX", "Word"),
                            ("XLSX", "Excel"),
                            ("PPTX", "PowerPoint"),
                            ("IMG", "Image"),
                            ("ZIP", "Archive"),
                            ("TXT", "Texte"),
                            ("OTHER", "Autre"),
                        ],
                        default="PDF",
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to="app.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fichier Uploadé",
                "verbose_name_plural": "Fichiers Uploadés",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reviewer_name",
                    models.CharField(
                        blank=True,
                        help_text="Optionnel: publié anonymement",
                        max_length=100,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("comment", models.TextField(max_length=1000)),
                ("is_verified_buyer", models.BooleanField(default=False)),
                ("helpful_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="app.listing",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_given",
                        to="app.studentprofile",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_received",
                        to="app.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avis",
                "verbose_name_plural": "Avis",
                "ordering": ["-created_at"],
                "unique_together": {("reviewer", "listing", "seller")},
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("MESSAGE", "Nouveau message"),
                            ("REVIEW", "Nouvel avis"),
                            ("LISTING", "Nouveau listing"),
                            ("FAVORITE", "Annonce favorite"),
                            ("SYSTEM", "Notification système"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("action_url", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="app.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "-created_at"],
                        name="app_notific_user_id_5559cb_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.listing",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_received",
                        to="app.studentprofile",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_sent",
                        to="app.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="app_message_recipie_38a9bc_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["status", "-created_at"], name="app_listing_status_187e8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["category", "status"], name="app_listing_categor_dd1e94_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "listing")},
        ),
        migrations.AddIndex(
            model_name="uploadedfile",
            index=models.Index(
                fields=["subject", "year"], name="app_uploade_subject_f4bea9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadedfile",
            index=models.Index(
                fields=["category", "is_public"], name="app_uploade_categor_b540de_idx"
            ),
        ),
    ]
