# Generated by Django 6.0.5 on 2026-06-13 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sample_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contacts_count',
            field=models.IntegerField(default=0, help_text='Nombre de personnes qui ont contacté'),
        ),
        migrations.AddField(
            model_name='listing',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Numéro WhatsApp (ex: +213671234567)', max_length=20),
        ),
        migrations.CreateModel(
            name='ListingContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_phone', models.CharField(blank=True, max_length=20)),
                ('buyer_name', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True, help_text='Message optionnel du demandeur')),
                ('contacted_via', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('PHONE', 'Téléphone'), ('PLATFORM', 'Platform')], default='PLATFORM', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacted_listings', to='app.studentprofile')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='app.listing')),
            ],
            options={
                'verbose_name': 'Demande de Contact',
                'verbose_name_plural': 'Demandes de Contact',
                'ordering': ['-created_at'],
                'unique_together': {('listing', 'buyer')},
            },
        ),
    ]
