"""
Django settings for unimarket project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import environ 
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8mw)+13pt!$7hpr27!d56i-u2gtd3j+=+jwe^olv*1z@6iixhw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

env = environ.Env(
    # Définir des valeurs par défaut si nécessaire (optionnel)
    DEBUG=(bool, False)
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'app',
    'mathfilters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app.middleware.SessionTimeoutMiddleware',  # Logout por inactividad
    'app.middleware.SecurityHeadersMiddleware',  # Headers de seguridad
]

ROOT_URLCONF = 'unimarket.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.active_categories',
            ],
        },
    },
]

WSGI_APPLICATION = 'unimarket.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.parse(os.environ.get('DATABASE_URL'))
    }

# ============================================
# CACHING - OPTIMISATION PERFORMANCES
# ============================================
# Cache en mémoire pour sessions et rate limiting
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unimarket-cache',
        'TIMEOUT': 3600,  # 1 heure
        'OPTIONS': {
            'MAX_ENTRIES': 10000,
        }
    }
}

# ============================================
# MESURES DE SÉCURITÉ - PARAMÈTRES DE SESSION
# ============================================
# Sécuriser les cookies de session
SESSION_COOKIE_SECURE = True  # True en production avec HTTPS
SESSION_COOKIE_HTTPONLY = True  # Empêcher l'accès JS aux cookies
SESSION_COOKIE_SAMESITE = 'Strict'  # Protection CSRF
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'  # ✅ Stocker en cache (PLUS RAPIDE)
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_AGE = 1800  # Session: 30 minutes
SESSION_SAVE_EVERY_REQUEST = False  # ✅ Optimisation: ne pas écrire BD chaque requête
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Fermer la session à la fermeture du navigateur

# ============================================
# MESURES DE SÉCURITÉ - CSRF
# ============================================
CSRF_COOKIE_SECURE = True  # True en production avec HTTPS
CSRF_COOKIE_HTTPONLY = True  # Empêcher l'accès JS au token CSRF
CSRF_COOKIE_SAMESITE = 'Strict'  # Protection contre les attaques inter-sites
CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000']

# ============================================
# MESURES DE SÉCURITÉ - AUTHENTIFICATION
# ============================================
# Authentification obligatoire pour les endpoints sensibles
LOGIN_REQUIRED = True
LOGIN_URL = 'login'

# Hachage des mots de passe renforcé
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',  # Plus fort si argon2 est installé
]


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# ============================================
# CONFIGURATION DES FICHIERS STATIQUES (PRODUCTION)
# ============================================

# 1. URL publique d'accès
STATIC_URL = '/static/'

# 2. Dossier final absolu requis par Render (Résout l'erreur STATIC_ROOT manquant)
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# 3. Forcer une liste vide pour supprimer le warning staticfiles.W004
# Cela évite que Django cherche un dossier "static" inexistant à la racine
STATICFILES_DIRS = []

# 4. Paramétrage des moteurs de stockage pour Django 4.2+ et WhiteNoise
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# ============================================
# CONFIGURATION DES FICHIERS MÉDIAS
# ============================================
MEDIA_URL = env('MEDIA_URL', default='/media/')

DEFAULT_MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
if os.environ.get('RENDER'):
    render_data_root = '/var/lib/render/project/data'
    if os.path.exists(render_data_root) or os.access(os.path.dirname(render_data_root), os.W_OK):
        DEFAULT_MEDIA_ROOT = os.path.join(render_data_root, 'media')
    else:
        DEFAULT_MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_ROOT = env('MEDIA_ROOT', default=DEFAULT_MEDIA_ROOT)

# Créer le dossier de médias si nécessaire (utile en production sur Render)
os.makedirs(MEDIA_ROOT, exist_ok=True)

# Validación de extensiones permitidas
ALLOWED_FILE_EXTENSIONS = ['pdf', 'docx', 'xlsx', 'pptx', 'jpg', 'jpeg', 'png', 'gif', 'zip', 'txt']
MAX_UPLOAD_SIZE = 50 * 1024 * 1024  # 50 MB

# ============================================
# MEDIDAS DE SEGURIDAD - HEADERS HTTP
# ============================================
# Prevenir clickjacking
X_FRAME_OPTIONS = 'DENY'

# Contenido Security Policy
SECURE_CONTENT_SECURITY_POLICY = {
    'default-src': ("'self'",),
    'script-src': ("'self'", "'unsafe-inline'", 'cdn.jsdelivr.net'),
    'style-src': ("'self'", "'unsafe-inline'", 'cdn.jsdelivr.net'),
    'img-src': ("'self'", 'data:', 'https:'),
    'font-src': ("'self'", 'data:', 'cdn.jsdelivr.net'),
    'connect-src': ("'self'",),
    'frame-ancestors': ("'none'",),
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# MEDIDAS DE SEGURIDAD - LOGGING
# ============================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django.db.backends': {
            'level': 'WARNING',
            'handlers': ['file'],
            'propagate': False,
        },
        'django.security': {
            'level': 'WARNING',
            'handlers': ['file'],
            'propagate': False,
        },
    },
}
